---
abstract: 'Perl interface to libnova'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  Cwd: 0
  ExtUtils::CBuilder: 0.15
  ExtUtils::ParseXS: 3.05
  Module::Build: 0
  Test::More: 0
configure_requires:
  File::Spec: 0
  FindBin: 0
  Module::Build: 0
  lib: 0
dynamic_config: 0
generated_by: 'Module::Build version 0.4008, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Astro-Nova
provides:
  Astro::Nova:
    file: lib/Astro/Nova.pm
    version: 0.07
  Astro::Nova::DMS:
    file: lib/Astro/Nova/DMS.pm
    version: 0
  Astro::Nova::EquPosn:
    file: lib/Astro/Nova/EquPosn.pm
    version: 0
  Astro::Nova::GalPosn:
    file: lib/Astro/Nova/GalPosn.pm
    version: 0
  Astro::Nova::HMS:
    file: lib/Astro/Nova/HMS.pm
    version: 0
  Astro::Nova::LnLatPosn:
    file: lib/Astro/Nova/LnLatPosn.pm
    version: 0
  Astro::Nova::ZoneDate:
    file: lib/Astro/Nova/ZoneDate.pm
    version: 0
requires:
  Carp: 0
  Exporter: 0
  File::Spec: 0
  XSLoader: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
