---
name: Astro-Nova
version: 0.06
author:
  - 'Steffen Mueller <smueller@cpan.org>'
abstract: Perl interface to libnova
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Cwd: 0
  ExtUtils::CBuilder: 0.15
  ExtUtils::Typemap: 0.03
  Module::Build: 0
  Test::More: 0
requires:
  Carp: 0
  Exporter: 0
  File::Spec: 0
  XSLoader: 0
configure_requires:
  File::Spec: 0
  FindBin: 0
  Module::Build: 0
  lib: 0
dynamic_config: 0
provides:
  Astro::Nova:
    file: lib/Astro/Nova.pm
    version: 0.06
  Astro::Nova::DMS:
    file: lib/Astro/Nova/DMS.pm
  Astro::Nova::EquPosn:
    file: lib/Astro/Nova/EquPosn.pm
  Astro::Nova::GalPosn:
    file: lib/Astro/Nova/GalPosn.pm
  Astro::Nova::HMS:
    file: lib/Astro/Nova/HMS.pm
  Astro::Nova::LnLatPosn:
    file: lib/Astro/Nova/LnLatPosn.pm
  Astro::Nova::ZoneDate:
    file: lib/Astro/Nova/ZoneDate.pm
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
distribution_type: module
